# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Unrotate
version:      1.03
version_from: lib/Log/Unrotate.pm
installdirs:  site
requires:
    File::Temp:                    0.15
    Test::Exception:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
